---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://mohong122.github.io/hugo_gh_blog"
title: "Hugo Blog Template for GitHub Pages"
...
